config/routes.rb
Cosc617app::Application.routes.draw do


  resources :journal_comments, :only => :create

  resources :review_requests, :only => [:create, :destroy, :index]

  resources :messages, :only => :create

  resources :private_forums , :only => [:create, :destroy] do
    member do
      get :messages
    end
  end

  resources :tution_sessions

  resources :decks do
    resources :flashcards
  end

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'


  #resources :posts
  #resources :topics
  #resources :forums
  root 'static_pages#home', :as => "root"

  get '/login', to: 'sessions#new', as: 'log_in'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'log_out'
  get '/users/sign_in', to: 'sessions#new'

  get '/register', to: 'users#new', as: 'register'
  get '/learner_home', to: 'static_pages#learner', :as => "learner_home"
  get '/teacher_home', to: 'static_pages#teacher', :as => "teacher_home"

  resources :profiles
  resources :sessions
  
  resources :users do
    collection do
      get :schedules
    end
  end

  resources :journals do
    resources :entries do
      member do
        get :review
      end
    end
  end
  
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :level, :title, :content, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :flashcards, :dependent => :destroy
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :journal
  has_many :comments, as: :commentable

  validates :title, presence: true
  validates :language, presence: true
  validates :entry, presence: true, length: {minimum: 6}

end

app/models/flashcard.rb
class Flashcard < ActiveRecord::Base
  belongs_to :deck
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :entries, :dependent => :destroy
  has_many :journal_comments
  belongs_to :user

  validates :title, :presence => true

end

app/models/journal_comment.rb
class JournalComment < ActiveRecord::Base
  belongs_to :entry
  belongs_to :user
  belongs_to :journal
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :private_forum

  def sender_user
    User.find(self.sender)
  end

  def receiver_user
    User.find(self.receiver)
  end
end

app/models/private_forum.rb
class PrivateForum < ActiveRecord::Base
  belongs_to :user
  belongs_to :tution_session
  has_many :messages, :dependent => :destroy

  def teacher
    self.tution_session.user
  end
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                  :integer          not null, primary key
#  username            :string(255)
#  first_name          :string(255)
#  last_name           :string(255)
#  email               :string(255)
#  country             :string(255)
#  time_zone           :string(255)
#  native_language     :string(255)
#  blog_url            :string(255)
#  description         :text
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  study_language      :string(255)
#

class Profile < ActiveRecord::Base

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	belongs_to :user
	validates :username, presence: true, uniqueness: true
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :country, presence: true
	validates :time_zone, presence: true
	validates :native_language, presence: true
	#validates :blog_url, presence: true
	#validates :description, presence: true
	#validates :avatar, presence: true

	default_scope order: 'profiles.created_at DESC'
end

app/models/review_request.rb
class ReviewRequest < ActiveRecord::Base
  belongs_to :entry
end

app/models/tution_session.rb
class TutionSession < ActiveRecord::Base

  belongs_to :user
  has_one :private_forum, :dependent => :destroy

  attr_accessor :start_time_date, :start_time_date, :start_time_time, :end_time_date, :end_time_time

  before_save :set_start_time, :set_end_time

  def set_start_time
    if start_time_date and start_time
      day = Date.strptime(self.start_time_date, "%m/%d/%Y")
      self.start_time = self.start_time.change(:year => day.year, :month => day.month, :day => day.day)
    end
  end 

  def set_end_time
    if end_time_date and end_time
      day = Date.strptime(self.end_time_date, "%m/%d/%Y")
      self.end_time = self.end_time.change(:year => day.year, :month => day.month, :day => day.day)
    end
  end

  def get_start_time
    self.start_time_date = start_time.strftime("%m/%d/%Y") if start_time
  end

  def get_end_time
    self.end_time_date = end_time.strftime("%m/%d/%Y") if end_time
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, :dependent => :destroy
  has_one :journal, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :topics, :dependent => :destroy
  has_many :journal_comments, :dependent => :destroy
  has_many :decks, :dependent => :destroy
  has_many :articles, :dependent => :destroy
  has_many :tution_sessions, :dependent => :destroy
  has_many :private_forums, :dependent => :destroy

  has_secure_password validations: false

  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 6}

  def is_teacher?
    self.teacher == true
  end

  def has_schedule(tution_session_id)
    self.private_forums.where("tution_session_id = ?", tution_session_id).present?
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def teacher
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  
    end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <%= image_tag "wordle.jpg", :style => "width:100%; margin-top:-40px;" %>
  <hr/>
  <h1>Language Learning</h1>
  <p class="lead">Redefining the language-learning process by offering a multitude of functionalities to make learning a range of languages (including English) not only easier, but also more engaging.</p>
</div>

<div class="row-fluid marketing">

  <div class="span4 sections">
    <h4> Learner </h4>
    <hr/>
    <h4><%= link_to "Learner", learner_home_path %></h4>
    <p>Start learning!</p>
  </div>

  <div class="span4 sections">
    <h4> Administrator </h4>
    <hr/>
    <h4><%= link_to "Administrator", '#' %></h4>
    <p>Manage Teachers and Students.</p>
  </div>

  <div class="span4 sections">
    <h4> Teacher </h4>
    <hr/>
    <h4><%= link_to "Teacher", teacher_home_path %></h4>
    <p>Guide your learners.</p>
  </div>
</div>

app/views/static_pages/learner.html.erb
<div class="jumbotron">
  <h1>Welcome, Learner!</h1>
  <p class="lead">Redefining the language-learning process by offering a multitude of functionalities to make learning a range of languages (including English) not only easier, but also more engaging.</p>
</div>

<hr>

<div class="row-fluid marketing">
  <div class="span6">

    <% if logged_in? %>

      <!-- if journal hasn't been created -->
      <% if current_user.journal == nil %>
      <h4><%= link_to "Create Journal", new_journal_path%>
      <% else %>
      <%= link_to "View Journal", '/journals/:id'%>
      <% end %>
      <br/>
      <%= link_to "Chat in Forum", forem_path%>
      <br/>
      <%= link_to "View Other Learners", profiles_path %>
      <br/>
      <%= link_to "Learn With Flashcards", decks_path %>


    <% else %>
      <%= link_to "Login for Journal", log_in_path %>
      <br/>
      <%= link_to "Login for Forum", log_in_path %>
    <% end %> </h4>

  </div>

</div>

app/views/static_pages/teacher.html.erb
<div class="jumbotron">
  <h1>Welcome, Teacher!</h1>
  <p class="lead">Redefining the language-learning process by offering a multitude of functionalities to make learning a range of languages (including English) not only easier, but also more engaging.</p>
</div>

<hr>

<div class="row-fluid marketing">
  <div class="span6">

    <% if logged_in? %>

      <!-- if journal hasn't been created -->
      <% if current_user.journal == nil %>
        <h4><%= link_to "Create Journal", new_journal_path%>
        <% else %>
          <%= link_to "View Journal", '/journals/:id'%>
        <% end %>
        <br/>
        <%= link_to "Chat in Forum", forem_path%>
        <br/>
        <%= link_to "View Other Learners", profiles_path %>
        <br/>
        <%= link_to "Learn With Flashcards", decks_path %>

        <% if current_user.is_teacher? %>
          <%= link_to "Create Article", new_article_path %> |
          <%= link_to "My Articles", articles_path %>
        <% end %>

      <% else %>
        <%= link_to "Login for Journal", log_in_path %>
        <br/>
        <%= link_to "Login for Forum", log_in_path %>
      <% end %> </h4>

  </div>

</div>